name: polyglot-observatory-3d

services:
  frontend-3d:
    build:
      context: .
      dockerfile: frontend-3d/Dockerfile
    environment:
      VITE_ANALYZER_API: http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - python-analyzer
      - java-benchmark
      - ruby-reporter

  frontend-js-widget:
    build:
      context: .
      dockerfile: frontend-js-widget/Dockerfile
    ports:
      - "4173:80"

  python-analyzer:
    build:
      context: .
      dockerfile: services/python-analyzer/Dockerfile
    environment:
      JAVA_BENCHMARK_URL: http://java-benchmark:8080
      RUBY_REPORTER_URL: http://ruby-reporter:4567
    ports:
      - "8000:8000"
    depends_on:
      - java-benchmark
      - ruby-reporter

  java-benchmark:
    build:
      context: .
      dockerfile: services/java-benchmark/Dockerfile
    ports:
      - "8080:8080"

  ruby-reporter:
    build:
      context: .
      dockerfile: services/ruby-reporter/Dockerfile
    ports:
      - "4567:4567"
