require "json"
require "webrick"

server = WEBrick::HTTPServer.new(
  Port: 4567,
  BindAddress: "0.0.0.0",
  AccessLog: [],
  Logger: WEBrick::Log.new($stdout, WEBrick::Log::WARN)
)

server.mount_proc "/health" do |_request, response|
  response["Content-Type"] = "application/json"
  response.body = JSON.generate({ status: "ok", service: "ruby-reporter" })
end

server.mount_proc "/report" do |request, response|
  unless request.request_method == "POST"
    response.status = 405
    response["Content-Type"] = "application/json"
    response.body = JSON.generate({ error: "method not allowed" })
    next
  end

  payload = request.body.to_s.empty? ? {} : JSON.parse(request.body)
  tests = Array(payload["tests"])
  score = Integer(payload["score"] || 0)
  language = payload["language"] || "unknown"
  workload_title = payload["workloadTitle"] || "Untitled Workload"

  passed = tests.count { |entry| entry["status"] == "pass" }
  warnings = tests.count { |entry| entry["status"] == "warn" }

  highlights = [
    "Ruby reporter generated a narrative summary.",
    "#{passed} checks passed and #{warnings} checks need attention."
  ]

  markdown = <<~MD
    # #{workload_title}

    Language: #{language}
    Score: #{score}

    ## Summary
    #{passed} checks passed and #{warnings} checks need attention.

    ## Test Signals
    #{tests.map { |entry| "- #{entry['name']}: #{entry['status']} - #{entry['detail']}" }.join("\n")}

    ## Reporter Notes
    - Generated by the Ruby reporting microservice.
    - Suitable for technical review or export.
  MD

  response["Content-Type"] = "application/json"
  response.body = JSON.generate(
    {
      summary: "#{workload_title} reviewed for #{language}.",
      markdown: markdown,
      highlights: highlights
    }
  )
end

trap("INT") { server.shutdown }
trap("TERM") { server.shutdown }

server.start
